"""OpenAPI security schemes used by the QMA HTTP boundary.

All schemes are non-raising extractors.  Endpoint business logic remains the
source of truth for whether a token is required, including its existing error
messages and query-parameter fallbacks.
"""

from fastapi.security import APIKeyHeader


qma_access_token_header = APIKeyHeader(
    name="X-QMA-Access-Token",
    scheme_name="X-QMA-Access-Token",
    auto_error=False,
    description="""Short-lived JWT granted after a successful invoice settlement. Used to unlock paid report endpoints.

**Retrieval:** The token is returned by the `/api/v1/payment/invoices/{invoice_id}/status` endpoint once the onchain payment reaches `confirmed` status.
**Fallback:** Can be passed via the `access_token` query parameter instead of the header (useful for GET-based downloads or iframe embeds).
**Enforcement:** Required on all 4 paid report endpoints (`/api/v1/providers/{provider_id}/preview`, `/api/v1/providers/{provider_id}/full-report`, `/api/v1/preview`, `/api/v1/analyze`). Missing, invalid, or expired tokens will trigger a `403 Forbidden` response.""",
)

qma_wallet_token_header = APIKeyHeader(
    name="X-QMA-Wallet-Token",
    scheme_name="X-QMA-Wallet-Token",
    auto_error=False,
    description="""Wallet profile session JWT, generated by signing a SIWE-like message proving wallet ownership.

**Retrieval:** Returned by the `/api/v1/wallets/{address}/session` endpoint.
**Optional vs Required:**
- **Required:** `/api/v1/wallets/{address}/reports/{entitlement_id}` strictly requires this token to view private report contents, throwing `403` if missing/invalid.
- **Optional:** `/api/v1/wallets/{address}/payments`, `/api/v1/metrics/wallet/{address}`, and `/api/v1/entitlements/wallet/{address}` accept this token. If present and valid, they return full private data. If absent or invalid, they gracefully fall back to returning redacted public data without throwing an error.
- **Not Used:** Wallet summary and alias routes do not use this token at all.""",
)

qma_admin_token_header = APIKeyHeader(
    name="x-qma-admin-token",
    scheme_name="x-qma-admin-token",
    auto_error=False,
    description="""Static administrative token for platform operations.

**Enforcement:**
- **Strictly Required:** Must be provided for mutation routes like Provider Toggle (`PATCH /api/v1/providers/{provider_id}/status`) and Creator Review (`POST /api/v1/providers/applications/{application_id}/review`). Throws `401 Unauthorized` if invalid.
- **Conditionally Required:** On listing routes (`GET /api/v1/providers`, `GET /api/v1/providers/{provider_id}`, `GET /api/v1/providers/{provider_id}/stats`), the token is only required if `include_disabled=true` is requested. If the token is missing/invalid while requesting disabled providers, it throws `401 Unauthorized`. If `include_disabled=false` (the default), the token is ignored and only public, enabled providers are returned.""",
)

qma_internal_secret_header = APIKeyHeader(
    name="x-qma-internal-secret",
    scheme_name="x-qma-internal-secret",
    auto_error=False,
)
